# Generated by Django 4.0.6 on 2022-08-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sizeclothes_sizefoot_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_clothes',
            field=models.ManyToManyField(blank=True, to='products.sizeclothes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_foot',
            field=models.ManyToManyField(blank=True, to='products.sizefoot'),
        ),
    ]
