# Generated by Django 4.0.6 on 2022-08-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_cat_alter_product_size_clothes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_clothes',
        ),
    ]
