# Generated by Django 4.0.6 on 2022-08-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_size_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeClothesM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizeclothes')),
            ],
        ),
    ]
