# Generated by Django 4.0.6 on 2022-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sizeclothesm2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_clothes',
            field=models.ManyToManyField(blank=True, through='products.SizeClothesM2M', to='products.sizeclothes'),
        ),
    ]
