# Generated by Django 4.0.6 on 2022-08-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_size_clothes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeclothesm2m',
            options={'verbose_name': 'Size_Clothe'},
        ),
        migrations.AlterField(
            model_name='prodpickture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_picktures', to='products.product'),
        ),
    ]
