# Generated by Django 4.0.6 on 2022-08-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.cart')),
                ('date', models.DateTimeField()),
            ],
            bases=('orders.cart',),
        ),
        migrations.AlterModelOptions(
            name='cartproductsm2m',
            options={'verbose_name': 'Product'},
        ),
    ]
