# Generated by Django 4.0.6 on 2022-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_cat'),
        ('orders', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='prod_in_cart', through='orders.CartProductsM2M', to='products.product'),
        ),
    ]
