# Generated by Django 4.0.6 on 2022-08-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_cat'),
        ('orders', '0006_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='prod_in_cart', through='orders.CartProductsM2M', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartproductsm2m',
            name='prod_foot_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizefoot'),
        ),
    ]
