# Generated by Django 4.0.6 on 2022-08-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductsm2m',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products_m2m', to='orders.cart'),
        ),
    ]
